spring.datasource.url=jdbc:postgresql://localhost:5432/docflow_dev
spring.datasource.username=postgres
spring.datasource.password=7904

# Dev-специфичные настройки
spring.jpa.show-sql=true  
logging.level.com.diploma.docflow=DEBUG 
file.upload-dir=uploads

jwt.secret=mySecretKeyForJWTTokenGenerationAndValidation2024DiplomaProject
jwt.expiration=86400000
# Добавляем тестовые данные при запуске
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:data-dev.sql
