spring.datasource.url=jdbc:postgresql://localhost:5432/docflow_dev
spring.datasource.username=postgres
spring.datasource.password=postgres

# Dev-специфичные настройки
spring.jpa.show-sql=true  # Показываем SQL для отладки
logging.level.com.diploma.docflow=DEBUG  # Детальные логи

# Добавляем тестовые данные при запуске
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data-dev.sql