# ================== База данных (PostgreSQL) ==================
spring.datasource.url=jdbc:postgresql://localhost:5432/docflow_dev
spring.datasource.username=postgres
spring.datasource.password=7904
spring.datasource.driver-class-name=org.postgresql.Driver

# ================== JPA / Hibernate ==================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ================== Файлы ==================
file.upload-dir=uploads

# ================== Логирование (более подробное для dev) ==================
logging.level.com.example.demo=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE